#! /usr/bin/env python

"""
Augment facilityfacts with LOS model data generated by nh_los_model_fits and known values
from an xls file.
"""

import json
import yaml_tools
import csv_tools
import sys

allKeySet, recs = yaml_tools.parse_all('facilityfacts10')
facDict = {r['abbrev']:r for r in recs}

with open('/home/welling/workspace/pyRHEA/models/OrangeCounty/nh_los_model_fit_parms.csv') as f:
    fitKeys, fitRecs = csv_tools.parseCSV(f)
fitDict = {r['abbrev']:r for r in fitRecs}

with open('/home/welling/workspace/pyRHEA/models/OrangeCounty/gatherdata7.csv') as f:
    hlosKeys, hlosRecs = csv_tools.parseCSV(f)
hlosDict = {r['Abbrev']: r for r in hlosRecs}

losModelProvStr = 'nh_los_model_fit.py r51 applied to Length_of_Stay_2007_to_2009_OC_Nursing_Homes-12-18-11_SMB_with_abbrev_RHEA.csv'
losModelDef = '$0*lognorm(mu=$1,sigma=$2)+(1-$0)*expon(lambda=$3)'
hlosModelProvStr = 'RHEA(Hosp&NH)_Inputs_Adult_2007_v03_06APR2012_KFW.xlsx:1_LOS'
hlosModelDef = 'lognorm(mu=$0,sigma=$1)'
newRecs = []
nModified = 0
for rec in recs:
    nR = rec.copy()
    abbrev = rec['abbrev']
    if abbrev in fitDict:
        nModified += 1
        fR = fitDict[abbrev]
        assert 'losModel' not in nR, "%s already has a LOS model" % abbrev
        nR['losModel'] = {'pdf': losModelDef,
                          'parms': [fR['k'], fR['mu'], fR['sigma'], fR['lmda']],
                          'nsamp': fR['nsamples'],
                          'negLogLikPerSample': fR['nllPerSamp'],
                          'prov': losModelProvStr}
    if abbrev in hlosDict:
        assert abbrev not in fitDict, '%s appears in both tables' % abbrev
        nModified += 1
        hR = hlosDict[abbrev]
        assert 'losModel' not in nR, "%s already has a LOS model" % abbrev
        nR['losModel'] = {'pdf': hlosModelDef,
                          'parms': [hR['mean_lnLOS'], hR['std_lnLOS']],
                          'prov': hlosModelProvStr}
        
        
    newRecs.append(nR)

print '%d of %d records modified' % (nModified, len(newRecs))
yaml_tools.save_all('facilityfacts11', newRecs)
