#! /usr/bin/env python

"""
Augment facilityfacts with LOS model data generated by nh_los_model_fits and known values
from an xls file.
"""

import json
import yaml_tools
import csv_tools
import sys

allKeySet, recs = yaml_tools.parse_all('facilityfacts11')
facDict = {r['abbrev']:r for r in recs}

with open('/home/welling/workspace/pyRHEA/models/OrangeCounty/gatherdata8.csv') as f:
    censusKeys, censusRecs = csv_tools.parseCSV(f)
censusDict = {r['abbrev']:r for r in censusRecs}

meanPopProvStr = "Average_Daily_Census_2007_for_OC_Nursing_Homes_10-31-11.xlsx:RHEA"

newRecs = []
nModified = 0
for rec in recs:
    nR = rec.copy()
    abbrev = rec['abbrev']
    changed = False
    
    # Mods apply only to NURSINGHOMEs
    if nR['category'] == 'NURSINGHOME':
        # Delete arbitrary one-year estimate of meanLOS
        if ('meanLos' in nR and nR['meanLOS']['value'] == 365.0 
            and nR['meanLOS']['prov'] == 
            'RHEA_Hosp-NH_Inputs_ADULT_2007_v03_06APR2012_properties_MRSA-STRAT-LOS.csv $C'):
            del nR['meanLOS']
            changed = True
            
        # Delete arbitrary meanPop value
        if 'meanPop' in nR and 'nBeds' not in nR:
            print 'funny record: %s' % abbrev
        if ('meanPop' in nR and nR['meanPop'] == float(nR['nBeds'])
            and nR['meanPop_prov'] ==
            'RHEA_Hosp-NH_Inputs_ADULT_2007_v03_06APR2012_properties_MRSA-STRAT-LOS.csv $B*$C/365'):
            del nR['meanPop']
            del nR['meanPop_prov']
            changed = True
            
        # Insert new census estimates
        if abbrev in censusDict:
            nR['meanPop'] = censusDict[abbrev]['Average2007Census']
            nR['meanPop_prov'] = meanPopProvStr
            changed = True
        
    if changed:
        nModified += 1        
    newRecs.append(nR)

print '%d of %d records modified' % (nModified, len(newRecs))
yaml_tools.save_all('facilityfacts12', newRecs)
